### ISSUE TITLE
udash-guide throw an error when build and run on different JDK

### ISSUE THREAD

**Issue by catap** [UdashFramework/udash-core#709]
I'm using JDK8 at laptop and when I build it and try to run via docker it throw an error:
```
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: java.io.FileReader.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V
	at io.udash.web.guide.markdown.MarkdownPagesEndpoint.$anonfun$render$1(MarkdownPagesEndpoint.scala:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ddworak** [comment]
We're running 11 LTS as the minimal version now, sorry.

**Comment by catap** [comment]
@ddworak wired, it is reproduced when I run on
```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
```

**Comment by catap** [comment]
How I reproduce it:
```
√ udash-core % java -version                                                                                                                              (git)-[save-bytes-as-file]
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
√ udash-core % sbt clean guide/docker:publishLocal                                                                                                        (git)-[save-bytes-as-file]
[info] welcome to sbt 1.4.4 (Azul Systems, Inc. Java 11.0.9.1)
[info] loading settings for project global-plugins from sbt-updates.sbt ...
[info] loading global plugins from /Users/catap/.sbt/1.0/plugins
....
[info] deleted: sha256:272764720b279985320eaa5484a4c690b71f926e445102b68323e4c7ede98143
[info] Total reclaimed space: 137.5MB
[info] Built image udash-guide with tags [0.9.0-SNAPSHOT]
[success] Total time: 95 s (01:35), completed 2 Dec 2020, 21:08:10
√ udash-core % docker run -p 8080:8080 --rm udash-guide:0.9.0-SNAPSHOT                                                                                    (git)-[save-bytes-as-file]
20:08:27.579 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @783ms to org.eclipse.jetty.util.log.Slf4jLog
...
```

go to `http://guide.udash.local:8080` and found this log in docker output

**Comment by ddworak** [comment]
The issue is not with your Java version - it's with the base docker image Java version, which seems to be `openjdk:8`. I'll fix it in the morning and think of some CI check to keep it working. If you need a quick workaround, try overriding `dockerBaseImage` in `guide-packager` to `openjdk:11` or similar.

**Comment by catap** [comment]
@ddworak lool, you wrote your comment at the same time when I wrote a commit message for my fix.

:)
